### ISSUE TITLE
OSError: Can't load tokenizer for 'bert-base-uncased

### ISSUE THREAD

**Issue by wpx-1** [showlab/mist#12]
I had follow the tutorial to run the code ,the paths of data also were modified.but I can not run the code successfully. there are the error infomation. 
Traceback (most recent call last):
  File "/work/shared_pool_data02/multi_modal/mist/main_agqa_v2.py", line 36, in <module>
    bert_tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
  File "/home/wpx/miniconda3/envs/mistenv/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1795, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.

**Comment by yangk-910** [comment]
You can download the relevant files of the bert-base-uncased model from huggingface.co and place them in the mist/"bert-base-uncased folder, then bert_tokenizer =BertTokenizer. from_ pretrained ("./bert-base-uncased"). You can try this to see if it works, that's what I did before with the robert model.
