### ISSUE TITLE
Training error Dataloader error

### ISSUE THREAD

**Issue by WeiYangBin** [showlab/mist#8]
Hello author
```
feats_shape: (9848, 32, 17, 512)
vids : <HDFS dataset "ids": shape (9848 ,), type “|S20”
feats_shape : (9848, 32, 17, 512)
2023-08-07 15:01:18,041 INFO number of train instances: 1600894
2023-08-07 15:01:18,041 INFO number of val instances: 669207
2023-08-07 15:01:18,046 INFO Set cosine schedule with 375180 iterations
> /home/weiyangbin/mist/data/agqa_clip_patch_loader.py(118)get_video_feature()
116.        # vid_ld = raw_vid_id If raw vid_id in self. frame_feats else raw _vid_id.strip("*mp4")
117
•-> 118   frame_feat = self frame_feats[vid_id][:, 0, :]
119         frame.feat = torch. from_numpy (frame_feat) . type (torch. float32)
120

ipdb> exit
Traceback (most recent call last):
File "main_agqa_v2.py", line 103, in <modules>
best_val_acc, best_epoch - train(nodel, train loader, a2v, optimizer, criterion, scheduler, epoch, args,
File "/hone/weiyangbin/mist/train/train mist.py' , line 91, in train for i, batch in enumerate(tratn_loader):
File " /home/welyangbin/anaconda3/envs/mist/llb/python3.8/site-packages/torch/uttls/data/dataloader.py",line530,in next
data = self._next_data()
File " /hone/weiyangbin/anaconda3/envs/nist/ltb/python3.8/site-packages/torch/utils/data/dataloader.py",line570,in next_data
data = self.dataset fetcher.fetch(index)
# may raise Stopiteration
File " /home/welyangbin/anaconda3/envs/mist/llb/python3.8/site-packages/torch/uttls/data/_uttls/fetch.py",line49, n fetch
data = [self.dataset[idx] for idx in possibly _batched_index]
File " /hone/welyangbin/anaconda3/envs/mist/lb/python3.8/site-packages/torch/uttls/data/_utils/fetch-py",line 49, i n <listcomp>
data = [self.dataset[idx] for idx in possibly_batched_index]
File " /hone/weiyangbin/mist/data/agqa_clip_patch_loader•py", line 133, in _getiten_ video _o, vtdeo_r- self.get_video _feature(raw vtd_id, width, height)
File"/hone/wetyangbin/mist/data/aga_clip_patch_loader.py",line 118, in get_video_feature
frame_ feat = self. frame feats [vid_id](:, 0, :]
File " /hone/weiyangbin/mist/data/agqa_clíp_patch_loader•py", line 118, in get_video_feature
frame_feat = self.frame_feats(vid_id](:, 0, :1
File " /hone/wetyangbin/anaconda3/envs/nist/lib/python3.8/bb.py",line88,in trace_dispatch return self.dispatch_line(frane)
File "/home/wetyangbtn/anaconda3/envs/mist/llb/python3.8/bb.py",1lne113,in dispatch_ line if self.quitting: raise BbQuit
bdb. BdbQuit
```
Above are my problems
and Where to donwload (train/val/test)*csv files

**Comment by WeiYangBin** [comment]
```
   self.frame_feats = {}
        with h5py.File(app_feat_file, 'r') as fp:
            vids = fp['ids']
            feats = fp['features']
            print(feats.shape)  # v_num, clip_num, feat_dim
            for id, (vid, feat) in enumerate(zip(vids, feats)):
                vid = vid.decode(encoding)
                self.frame_feats[vid] = feat
```
Your shape looks like this （print(feats.shape)  # v_num, clip_num, feat_dim）, and mine looks like this （feats_shape : (9848, 32, 17, 512)）
